temporaryFile <- tempfile()
download.file("https://www.dropbox.com/s/zjf0lm830wzmkwz/snmp-delta.csv?dl=0",
                  destfile=temporaryFile, method="curl", extra="-L")
snmpData = read.csv(temporaryFile)
interface <- c(snmpData$if.)
outUCastPkts <- c(snmpData$outUCastPkts)
inOctets <- c(snmpData$inOctets)
outOctets <- c(snmpData$outOctets)
inUcastPkts <- c(snmpData$inUcastPkts)
outNUCastPkts <- c(snmpData$outNUCastPkts)
inNUcastPkts <- c(snmpData$inNUcastPkts)
data <- data.frame(if.=interface,outUCastPkts=outUCastPkts,inOctets=inOctets,outOctets=outOctets,inUcastPkts=inUcastPkts,outNUCastPkts=outNUCastPkts,inNUcastPkts=inNUcastPkts )
data
interface1_outUcast <- sum(data[data$if. == "1","outUCastPkts" ])
interface1_inoctets <- sum(data[data$if. == "1","inOctets" ])
interface1_ooctets <- sum(data[data$if. == "1","outOctets" ])
interface1_inUcastpkts <- sum(data[data$if. == "1","inUcastPkts" ])
interface1_outnu <- sum(data[data$if. == "1","outNUCastPkts" ])
interface1_innu <- sum(data[data$if. == "1","inNUcastPkts" ])
data1 <- data.frame(if.=1, outUCastPkts=interface1_outUcast)
interface2_outUcast <- sum(data[data$if. == "2","outUCastPkts" ])
interface2_inoctets <- sum(data[data$if. == "2","inOctets" ])
interface2_ooctets <- sum(data[data$if. == "2","outOctets" ])
interface2_inUcastpkts <- sum(data[data$if. == "2","inUcastPkts" ])
interface2_outnu <- sum(data[data$if. == "2","outNUCastPkts" ])
interface2_innu <- sum(data[data$if. == "2","inNUcastPkts" ])
a <- c(1,2)
a1 <- c()
data1 <- data.frame(if.=a,outUCastPkts=interface1_outUcast)
data1
interface3_outUcast <- sum(data[data$if. == "3","outUCastPkts" ])
interface3_inoctets <- sum(data[data$if. == "3","inOctets" ])
interface3_ooctets <- sum(data[data$if. == "3","outOctets" ])
interface3_inUcastpkts <- sum(data[data$if. == "3","inUcastPkts" ])
interface3_outnu <- sum(data[data$if. == "3","outNUCastPkts" ])
interface3_innu <- sum(data[data$if. == "3","inNUcastPkts" ])

interface6_outUcast <- sum(data[data$if. == "6","outUCastPkts" ])
interface6_inoctets <- sum(data[data$if. == "6","inOctets" ])
interface6_ooctets <- sum(data[data$if. == "6","outOctets" ])
interface6_inUcastpkts <- sum(data[data$if. == "6","inUcastPkts" ])
interface6_outnu <- sum(data[data$if. == "6","outNUCastPkts" ])
interface6_innu <- sum(data[data$if. == "6","inNUcastPkts" ])

interface7_outUcast <- sum(data[data$if. == "7","outUCastPkts" ])
interface7_inoctets <- sum(data[data$if. == "7","inOctets" ])
interface7_ooctets <- sum(data[data$if. == "7","outOctets" ])
interface7_inUcastpkts <- sum(data[data$if. == "7","inUcastPkts" ])
interface7_outnu <- sum(data[data$if. == "7","outNUCastPkts" ])
interface7_innu <- sum(data[data$if. == "7","inNUcastPkts" ])

interface9_outUcast <- sum(data[data$if. == "9","outUCastPkts" ])
interface9_inoctets <- sum(data[data$if. == "9","inOctets" ])
interface9_ooctets <- sum(data[data$if. == "9","outOctets" ])
interface9_inUcastpkts <- sum(data[data$if. == "9","inUcastPkts" ])
interface9_outnu <- sum(data[data$if. == "9","outNUCastPkts" ])
interface9_innu <- sum(data[data$if. == "9","inNUcastPkts" ])
interface10_outUcast <- sum(data[data$if. == "10","outUCastPkts" ])
interface10_inoctets <- sum(data[data$if. == "10","inOctets" ])
interface10_ooctets <- sum(data[data$if. == "10","outOctets" ])
interface10_inUcastpkts <- sum(data[data$if. == "10","inUcastPkts" ])
interface10_outnu <- sum(data[data$if. == "10","outNUCastPkts" ])
interface10_innu <- sum(data[data$if. == "10","inNUcastPkts" ])

interface11_outUcast <- sum(data[data$if. == "11","outUCastPkts" ])
interface11_inoctets <- sum(data[data$if. == "11","inOctets" ])
interface11_ooctets <- sum(data[data$if. == "11","outOctets" ])
interface11_inUcastpkts <- sum(data[data$if. == "11","inUcastPkts" ])
interface11_outnu <- sum(data[data$if. == "11","outNUCastPkts" ])
interface11_innu <- sum(data[data$if. == "11","inNUcastPkts" ])

interface2 <- c(data[data$if. == "2", ])
interface3 <- c(data[data$if. == "3", ])
interface6 <- c(data[data$if. == "6", ])
interface7 <- c(data[data$if. == "7", ])
interface9 <- c(data[data$if. == "9", ])
interface10 <- c(data[data$if. == "10", ])
interface11 <- c(data[data$if. == "11", ])






